url             = 'http://kroseii.bigcartel.com/' #url to monitor
wait_time       =  120 #customizable time to wait to check for changes IE every 5 secs
user            = 'urgmailhere@gmail.com' #emailuser@gmail.com
pwd             = 'iifief iejfi ieief iei'  #app password generated by google https://security.google.com/settings/security/apppasswords
recipient       = 'emailtosendtohere@gmail.com' #recievingemail@gmail.com
subject         = 'SITE UPDATED' #message subject
body            = 'CHANGE AT ' + str(url) #message body 
