#-----------------------------------------BASICS-------------------------------------
url                 = 'https://pastebin.com/' # url to monitor
wait_time           =  10 #customizable time to wait to check for changes IE every 20 secs


#------------------------------------GMAIL SECTION----------------------------------

notify              = False #True to notify via email on change False

user                = '' #emailuser@gmail.com
pwd                 = ''  #app password generated by google IE "djfj rubi sifu sofi"
recipient           = '' #recievingemail@gmail.com


# ----------------------------------TWITTER SECTION------------------------------------

tweet               = False #True to tweet on change, False not to

consumer_key        = ''
consumer_secret     = ''
access_token        = ''
access_token_secret = ''


 #---------------------------------SMS SECTION------------------------------------------
#https://www.twilio.com/console/account/settings

text                 = True #True to send text, false to not

accountSID          = ''
authToken           = ''
myNumber            = '' #number to send text messages to
twilioNumber        = '' #twillio phone number

 
 
'''

always remember that this isn't a "shopify monitor" or "restock monitor", it just watches for even the smallest change in the content of a site.
So if it starts spamming your twitter feed make sure you're there to turn it off etc. to avoid getting banned or losting all your followers.
Same thing with the email, it will spam until you can turn it off essentially.

'''
