url             = 'http://kroseii.bigcartel.com/' #url to monitor
wait_time       =  120 #customizable time to wait to check for changes IE every 5 secs
user            = 'gmailuserhere@gmail.com' #emailuser@gmail.com
pwd             = 'xiwefiuwheifuh'  #app password generated by google IE "djfj rubi sifu sofi"
recipient       = 'recievingmail@gmail.com' #recievingemail@gmail.com
subject         = 'SITE UPDATED' #message subject
body            = 'CHANGE AT ' + str(url) #message body 
notify          = True #True to notify via email on change False not to